const = {
    'gravityMars': 3.71,
    'airDensity': 0.01,
    'soundSpeed': 220,
    'cl': 1.6,
    'cd': 0.03,
    'irradiance': 590,
    'solarPanelDensity': 1.76,
    'batteryEnergyDensity': 333.33,
    'batteryPowerDensity': 300,
    'takeoffBatteryPowerDensity': 1317,
    'takeoffBatteryEnergyDensity': 437,
    'bladeDensity': 1500,
    'allowedStress':3.5e9*0.3,
    't/c': 0.012,
    'visc_cr': 5.167E-4,
    'cruiseSpeed': 112,
    'batteryVolume': 450,  # Wh/L
    'ultimateLoad': 4.4,
    'takeOffLoad': 1.1,
    'designRange': 1e6,
    'takeOffTime': 600,
    'margin': 0.1,
    'payloadMass': 400,
    'maxMass': 3000
}

aircraftParameters = {
    'wingArea': 0,
    'AR': 15,
    'ARmin': 10,
    'cruiseThrust': 0,
    'rotorRadius': 0,
    'wingspan': 0,
    'chord': 0,
    'wingMass': 0,
    'tailMass': 0,
    'bodyMass': 0,
    'rotorMass': 0,
    'batteryMass': 0,
    'panelMass': 0,
    'totalRotors': 4,
    'bladesPerRotor': 6,
    'coaxial': True,
    'horsepowerPerEngine': 0,
    'totalPower': 0,
    'wingbraced': True,
    'totalMass': 0,
    'aircraftVolume': 0
}
