import numpy as np


def wing_bending(MTOM, wingspan, engineMass, rotorMass, n_rotors, wingMass):
    g = 3.71
    thrustPerEngine = 1.1 * MTOM * g / 2
    engineWeight = engineMass * g + rotorMass * n_rotors * g
    wingWeight = wingMass * g

    momentAtBase = (thrustPerEngine - engineWeight) * wingspan/2 - wingWeight * wingspan/4
    return momentAtBase


if __name__ == '__main__':
    # Define constants
    gm = 3.71
    MTOM = 3000

    # Define masses
    cabinMass = ...
    fuselageMass = ...
    tailPoleMass = ...
    tailMass = ...
    wingMass = ...
    engineMass = ...
    rotorMass = ...

    # Define dimensions
    cabinLength = ...
    fuselageLength = ...
    fuselageWidth = ...
    tailPoleLength = ...
    chordLength = ...
    wingSpan = ...
    nacelleWidth = ...
    rotorBladeLength = ...

